gamechanger_admin/protected/controllers/DealsController.php
<?php

class DealsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','pending','approved','expired','disapproved','fullfilled','approvedByAdmin','disapprovedByAdmin','fullfilledByAdmin','paidToAgent'),
				'users'=>array('@'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
//				'actions'=>array('create','update'),
				'actions'=>array('create'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
//				'actions'=>array('admin','delete'),
				'actions'=>array('delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
//		$this->render('view',array(
//			'model'=>$this->loadModel($id),
//		));
		$model=$this->loadModel($id);
                
                $model->setScenario('numeric_validation');
                $this->performAjaxValidation($model);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Deals']))
		{
			$model->attributes=$_POST['Deals'];
                        if($model->validate()){
                            if($model->save(false)) {
                                    Yii::app()->user->setFlash('deals-form', "Successfully Updated!");
                                    $this->redirect(array('view','id'=>$model->dealid));
                            }
                        }
		}

		$this->render('update',array(
			'model'=>$model,
		));                
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Deals;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Deals']))
		{
			$model->attributes=$_POST['Deals'];
			if($model->save()) {
                                Yii::app()->user->setFlash('deals-form', "Successfully Inserted!");
				$this->redirect(array('view','id'=>$model->dealid));
                        }
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
//	public function actionUpdate($id)
//	{
//		$model=$this->loadModel($id);
//
//		// Uncomment the following line if AJAX validation is needed
//		// $this->performAjaxValidation($model);
//
//		if(isset($_POST['Deals']))
//		{
//			$model->attributes=$_POST['Deals'];
//			if($model->save())
//				$this->redirect(array('view','id'=>$model->dealid));
//		}
//
//		$this->render('update',array(
//			'model'=>$model,
//		));
//	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
//		$dataProvider=new CActiveDataProvider('Deals');
//		$this->render('index',array(
//			'dataProvider'=>$dataProvider,
//		));
                $model=new Deals('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Deals']))
			$model->attributes=$_GET['Deals'];

		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	 * Manages all models.
	 */
//	public function actionAdmin()
//	{
//		$model=new Deals('search');
//		$model->unsetAttributes();  // clear any default values
//		if(isset($_GET['Deals']))
//			$model->attributes=$_GET['Deals'];
//
//		$this->render('admin',array(
//			'model'=>$model,
//		));
//	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Deals the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Deals::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Deals $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='deals-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
        
        
       public function actionPending()
	{
               $criteria=new CDbCriteria;
               $criteria->condition= "dealstatusid='0'";
               $criteria->order = 'dealid DESC';
               $dataProvider=new CActiveDataProvider('Deals',array('criteria'=>$criteria ,'pagination'=>array('pageSize'=>Yii::app()->params->pageSize)));

		$this->render('pending',array(
			'dataProvider'=>$dataProvider,                                              
		));
	}
               
        public function actionExpired()
	{
               $criteria=new CDbCriteria;
               $criteria->condition= "dealstatusid='3'";
               $criteria->order = 'dealid DESC';
               $dataProvider=new CActiveDataProvider('Deals',array('criteria'=>$criteria ,'pagination'=>array('pageSize'=>Yii::app()->params->pageSize)));

		$this->render('expired',array(
			'dataProvider'=>$dataProvider,                                              
		));
	}
               
        public function actionApproved()
	{
               $criteria=new CDbCriteria;
               $criteria->condition= "dealstatusid='1'";
               $criteria->order = 'dealid DESC';
               $dataProvider=new CActiveDataProvider('Deals',array('criteria'=>$criteria ,'pagination'=>array('pageSize'=>Yii::app()->params->pageSize)));

		$this->render('approved',array(
			'dataProvider'=>$dataProvider,
                       
		));
	}
        
        public function actionDisapproved()
	{                           
               $criteria=new CDbCriteria;
               $criteria->condition= "dealstatusid='4'";
               $criteria->order = 'dealid DESC';
               $dataProvider=new CActiveDataProvider('Deals',array('criteria'=>$criteria ,'pagination'=>array('pageSize'=>Yii::app()->params->pageSize)));

		$this->render('disapproved',array(
			'dataProvider'=>$dataProvider,                       
		));
	}
        
        
        public function actionFullfilled()
	{              
               $criteria=new CDbCriteria;
               $criteria->condition= "dealstatusid='2' OR dealstatusid='5'";
               $criteria->order = 'dealid DESC';
               $dataProvider=new CActiveDataProvider('Deals',array('criteria'=>$criteria ,'pagination'=>array('pageSize'=>Yii::app()->params->pageSize)));

		$this->render('fullfilled',array(
			'dataProvider'=>$dataProvider,
                       
		));
	}
        
        public function actionApprovedByAdmin($dealId) {
                                       
            $model = $this->loadModel($dealId);
            $isLast = $model->isLastDeal();
        
            //Capture the cost per this deal
            $captureInfo['COMPLETETYPE'] = $isLast ? 'complete' : 'NotComplete';//when complete paypal do voide automatically
            $captureInfo['AUTHORIZATIONID'] = $model->order->payment->transactionid;
            $captureInfo['AMOUNT'] = $model->cost;
            $paymentResult = Yii::app()->paypal->DoCapture($captureInfo);
            //CVarDumper::dump($paymentResult, 1000, true);
            //Detect payment errors
            if (!Yii::app()->paypal->isCallSucceeded($paymentResult)) {
                if (Yii::app()->paypal->apiLive === true) {
                    //Live mode basic error message
                    $error = 'We were unable to process your request. Please try again later (live mode)';
                } else {
                    //Sandbox output the actual error message to dive in.
                    $error = $paymentResult['L_LONGMESSAGE0'];
                }
                $model->order->payment->msg = $error;
                $model->order->payment->save();                
                Yii::app()->user->setFlash('deals-error', $error);
                $this->redirect(array('view','id'=>$dealId));
                //Yii::app()->end();
            } else {
                //capture payment was completed successfully 
                $model->order->payment->captured += $paymentResult['AMT']; //same PARENTTRANSACTIONID
                $model->order->payment->msg = $paymentResult['PAYMENTSTATUS'];
                $model->order->payment->status = $isLast ? 3 : 2;
                $model->order->payment->save();
                if($isLast){
                    $model->order->status = 1;
                    $model->order->save();
                }
            }

gamechanger_admin/protected/views/deals/accepted.php
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Manage Accepted Orders</h1>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php //echo CHtml::link('<i class="fa fa-file-o"></i> Create', Yii::app()->createUrl('deals/create'), array('class'=>'btn btn-default')); ?>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php $this->widget('zii.widgets.grid.CGridView', array(
                'id'=>'deals-grid',
                'dataProvider'=>$dataProvider,
                //'filter'=>$model,
                'columns'=>array(
        		'dealid',
		//'orderid',
		//'dealstatusid',
		
                 array(
                            'name'=>'athleteid',
                            'type'=>'raw',
                           
                            'value'=>function($data,$row) use (&$model){
                                $result = Deals::model()->GetAthleteName($data->athleteid);
                                return Deals::model()->valuesArray['name'];
                             },
                      
                      
                      ),   
	     
                array(
                            'name'=>'agentid',
                            'type'=>'raw',
                           
                            'value'=>function($data,$row) use (&$model){
                                $result = Deals::model()->GetAgentName($data->agentid);
                                return Deals::model()->valuesArray['name'];
                             },
                      
                      
                        ),
                                     
                 array(
                            'name'=>'dealtype',
                            'type'=>'raw',
                            'value'=>'getdealtype($data->dealtype)',
                      
                        ),                     
		'cost',
                'dealrequesteddate',    
                                     
                array(
                    'name'=>'dealid',
                    'header'=>'Fullfill',
                    'type' => 'raw',
                    'value'=> 'setAsFullfilled($data->dealid)',
                    'filter'=>FALSE ,
                ),  
		/*
		'dealrequesteddate',
		'image',
		'description',
		'campaigndate',
		'campaigntime',
		'dealapproveddate',
		'dealfullfilleddate',
		'dateofpaymentbybrand',
		'dateofpaymenttoagent',
		'agentid',
		'agentsharepercentage',
		'agentshare',
		'fulfill_engagement',
		'fulfill_reach',
		'fullfill_paidtoagent',
		*/
                        array(
                                'class'=>'CButtonColumn',
                                'template'=>'{view}',
                        ),
                ),
        )); ?>
        
        
          <?php
        function setAsFullfilled($dealid) {
                $deals = Deals::model()->find('dealid = '.$dealid.' AND dealstatusid=2' );
                if($deals) {
                     echo CHtml::link("Set as Fullfilled",array("deals/fullfilledByAdmin",array("DealId"=>$dealid)),array("confirm" => "Do you wish to mark this as Fullfilled?",'class'=>'btn btn-info')); 
                } 
            }
        
            function getdealtype($dealtype) {
                
                if($dealtype==0) {
                     echo 'Twitter';
                } else {  
                     echo  'Instagram';
                }
            }
        
        ?>
    </div>
</div>
<!-- /.row -->

gamechanger_admin/protected/views/deals/approved.php
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Manage Approved Deals</h1>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php //echo CHtml::link('<i class="fa fa-file-o"></i> Create', Yii::app()->createUrl('deals/create'), array('class'=>'btn btn-default')); ?>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php
        $this->widget('zii.widgets.grid.CGridView', array(
            'id' => 'deals-grid',
            'dataProvider' => $dataProvider,
            //'filter'=>$model,
            'columns' => array(
                'dealid',
                //'orderid',
                //'dealstatusid',
                'brandName',
                array(
                    'name' => 'athleteid',
                    'type' => 'raw',
                    'value' => '$data->GetAthleteName()',
                ),
                array(
                    'name' => 'agentid',
                    'type' => 'raw',
                    'value' => '$data->GetAgentName()',
                ),
                array(
                    'name' => 'dealtype',
                    'type' => 'raw',
                    'value' => 'getdealtype($data->dealtype)',
                ),
                array(
                    'name' => 'cost',
                    'header' => 'Deal Cost (AUD)',
                    'htmlOptions' => array('class' => 'right'),
                ),
                array(
                    'name' => 'dealrequesteddate',
                    'htmlOptions' => array('class' => 'right'),
                ),
                array(
                    'name' => 'dealid',
                    'header' => 'Fulfill',
                    'type' => 'raw',
                    'value' => 'setAsFullfilled($data->dealid)',
                    'filter' => FALSE,
                ),
                /*
                  'dealrequesteddate',
                  'image',
                  'description',
                  'campaigndate',
                  'campaigntime',
                  'dealapproveddate',
                  'dealfullfilleddate',
                  'dateofpaymentbybrand',
                  'dateofpaymenttoagent',
                  'agentid',
                  'agentsharepercentage',
                  'agentshare',
                  'fulfill_engagement',
                  'fulfill_reach',
                  'fullfill_paidtoagent',
                 */
                array(
                    'class' => 'CButtonColumn',
                    'template' => '{view}',
                ),
            ),
        ));
        ?>

        <?php

        function setAsFullfilled($dealid) {
            $deals = Deals::model()->find('dealid = ' . $dealid . ' AND dealstatusid=1');
            if ($deals) {
                echo CHtml::link("Set as Fulfilled", array("deals/fullfilledByAdmin", array("DealId" => $dealid)), array("confirm" => "Do you wish to mark this as Fulfilled?", 'class' => 'btn btn-info'));
            }
        }

        function getdealtype($dealtype) {

            if ($dealtype == 0) {
                echo 'Twitter';
            } else {
                echo 'Instagram';
            }
        }
        ?>

    </div>
</div>
<!-- /.row -->

gamechanger_admin/protected/views/deals/disapproved.php
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Disapproved Deals</h1>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php //echo CHtml::link('<i class="fa fa-file-o"></i> Create', Yii::app()->createUrl('deals/create'), array('class'=>'btn btn-default')); ?>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php
        $this->widget('zii.widgets.grid.CGridView', array(
            'id' => 'deals-grid',
            'dataProvider' => $dataProvider,
            //'filter'=>$model,
            'columns' => array(
                'dealid',
                //'orderid',
                //'dealstatusid',
                'brandName',
                array(
                    'name' => 'athleteid',
                    'type' => 'raw',
                    'value' => '$data->GetAthleteName()',
                ),
                array(
                    'name' => 'agentid',
                    'type' => 'raw',
                    'value' => '$data->GetAgentName()',
                ),
                array(
                    'name' => 'dealtype',
                    'type' => 'raw',
                    'value' => 'getdealtype($data->dealtype)',
                ),
                array(
                    'name' => 'cost',
                    'header' => 'Cost (AUD)',
                    'htmlOptions' => array('class' => 'right'),
                ),
                array(
                    'name' => 'dealrequesteddate',
                    'htmlOptions' => array('class' => 'right'),
                ),               
                /*
                  'dealrequesteddate',
                  'image',
                  'description',
                  'campaigndate',
                  'campaigntime',
                  'dealapproveddate',
                  'dealfullfilleddate',
                  'dateofpaymentbybrand',
                  'dateofpaymenttoagent',
                  'agentid',
                  'agentsharepercentage',
                  'agentshare',
                  'fulfill_engagement',
                  'fulfill_reach',
                  'fullfill_paidtoagent',
                 */
                array(
                    'class' => 'CButtonColumn',
                    'template' => '{view}',
                ),
            ),
        ));
        ?>


        <?php
//
//        function setAsFullfilled($dealid) {
//            $deals = Deals::model()->find('dealid = ' . $dealid . ' AND dealstatusid=2');
//            if ($deals) {
//                echo CHtml::link("Set as Fullfilled", array("deals/fullfilledByAdmin", array("DealId" => $dealid)), array("confirm" => "Do you wish to mark this as Fullfilled?", 'class' => 'btn btn-info'));
//            }
//        }

        function getdealtype($dealtype) {

            if ($dealtype == 0) {
                echo 'Twitter';
            } else {
                echo 'Instagram';
            }
        }
        ?>
    </div>
</div>
<!-- /.row -->

gamechanger_admin/protected/views/deals/expired.php
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Expired Deals</h1>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php //echo CHtml::link('<i class="fa fa-file-o"></i> Create', Yii::app()->createUrl('deals/create'), array('class'=>'btn btn-default')); ?>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php
        //CVarDumper::dump($_SERVER, 1000, true);
        $this->widget('zii.widgets.grid.CGridView', array(
            'id' => 'deals-grid',
            'dataProvider' => $dataProvider,
            //'filter'=>$model,
            'columns' => array(
                'dealid',
                //'orderid',
                //'dealstatusid',
                'brandName',
                array(
                    'name' => 'AthleteName',
                    'type' => 'raw',
                //'value' => '$data->GetAthleteName()',
                ),
                array(
                    'name' => 'AgentName',
                    'type' => 'raw',
                //'value' => '$data->GetAgentName()',
                ),
                array(
                    'name' => 'dealType',
                //'type' => 'raw',
                //'value' => 'getdealtype($data->dealtype)',
                ),
                array(
                    'name' => 'cost',
                    'header' => 'Deal Cost (AUD)',
                    'htmlOptions' => array('class' => 'right'),
                ),
                array(
                    'name' => 'dealrequesteddate',
                    'htmlOptions' => array('class' => 'right'),
                ),
                array(
                    'name' => 'daysSinceOrdered',
                    'htmlOptions' => array('class' => 'right'),
                ),
                /* 'image',
                  'description',
                  'campaigndate',
                  'campaigntime',
                  'dealapproveddate',
                  'dealfullfilleddate',
                  'dateofpaymentbybrand',
                  'dateofpaymenttoagent',
                  'agentid',
                  'agentsharepercentage',
                  'agentshare',
                  'fulfill_engagement',
                  'fulfill_reach',
                  'fullfill_paidtoagent',
                 */
                array(
                    'class' => 'CButtonColumn',
                    'template' => '{view}',
                ),
            ),
        ));
        ?>

        <?php

        function getdealtype($dealtype) {

            if ($dealtype == 0) {
                echo 'Twitter';
            } else {
                echo 'Instagram';
            }
        }
        ?>
    </div>
</div>
<!-- /.row -->

gamechanger_admin/protected/views/deals/fullfilled.php
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Manage Fulfilled Deals</h1>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php //echo CHtml::link('<i class="fa fa-file-o"></i> Create', Yii::app()->createUrl('deals/create'), array('class'=>'btn btn-default')); ?>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php
        $this->widget('zii.widgets.grid.CGridView', array(
            'id' => 'deals-grid',
            'dataProvider' => $dataProvider,
            //'filter'=>$model,
            'columns' => array(
                'dealid',
                //'orderid',
                //'dealstatusid',
                'brandName',
                array(
                    'name' => 'athleteid',
                    'type' => 'raw',
                    'value' => '$data->GetAthleteName()',
                ),
                array(
                    'name' => 'agentid',
                    'type' => 'raw',
                    'value' => '$data->GetAgentName()',
                ),
                array(
                    'name' => 'dealtype',
                    'type' => 'raw',
                    'value' => 'getdealtype($data->dealtype)',
                ),
                array(
                    'name' => 'cost',
                    'header' => 'Deal Cost (AUD)',
                    'htmlOptions' => array('class' => 'right'),
                ),
                array(
                    'name' => 'dealrequesteddate',
                    'htmlOptions' => array('class' => 'right'),
                ),
                array(
                    'name' => 'dealid',
                    'header' => 'Paid to Agent',
                    'type' => 'raw',
                    'value' => 'setPaidToAgent($data->dealid)',
                    'filter' => FALSE,
                ),
                /*
                  'dealrequesteddate',
                  'image',
                  'description',
                  'campaigndate',
                  'campaigntime',
                  'dealapproveddate',
                  'dealfullfilleddate',
                  'dateofpaymentbybrand',
                  'dateofpaymenttoagent',
                  'agentid',
                  'agentsharepercentage',
                  'agentshare',
                  'fulfill_engagement',
                  'fulfill_reach',
                  'fullfill_paidtoagent',
                 */
                array(
                    'class' => 'CButtonColumn',
                    'template' => '{view}',
                ),
            ),
        ));
        ?>
        <?php

        function setPaidToAgent($dealid) {
            $deals = Deals::model()->find('dealid = ' . $dealid . ' AND fullfill_paidtoagent=0');
            if ($deals) {
                echo CHtml::link("Set as Paid to Agent", array("deals/paidToAgent", array("DealId" => $dealid)), array("confirm" => "Do you wish to mark this as Paid to agent?", 'class' => 'btn btn-info'));
            } else {
                echo 'Paid To Agent';
            }
        }

        function getdealtype($dealtype) {

            if ($dealtype == 0) {
                echo 'Twitter';
            } else {
                echo 'Instagram';
            }
        }
        ?>

    </div>
</div>
<!-- /.row -->

gamechanger_admin/protected/views/deals/index.php
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Manage Deals</h1>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php echo CHtml::link('<i class="fa fa-file-o"></i> Create', Yii::app()->createUrl('deals/create'), array('class'=>'btn btn-default')); ?>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php $this->widget('zii.widgets.grid.CGridView', array(
                'id'=>'deals-grid',
                'dataProvider'=>$model->search(),
                'filter'=>$model,
                'columns'=>array(
        		'dealid',
		'orderid',
		'dealstatusid',
		'athleteid',
		'dealtype',
		'cost',
		/*
		'dealrequesteddate',
		'image',
		'description',
		'campaigndate',
		'campaigntime',
		'dealapproveddate',
		'dealfullfilleddate',
		'dateofpaymentbybrand',
		'dateofpaymenttoagent',
		'agentid',
		'agentsharepercentage',
		'agentshare',
		'fulfill_engagement',
		'fulfill_reach',
		'fullfill_paidtoagent',
		*/
                        array(
                                'class'=>'CButtonColumn',
                                'template'=>'{view} {delete}',
                        ),
                ),
        )); ?>
    </div>
</div>
<!-- /.row -->

gamechanger_admin/protected/views/deals/pending.php
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Manage Pending Deals</h1>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php //echo CHtml::link('<i class="fa fa-file-o"></i> Create', Yii::app()->createUrl('deals/create'), array('class'=>'btn btn-default')); ?>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <?php
        $this->widget('zii.widgets.grid.CGridView', array(
            'id' => 'deals-grid',
            'dataProvider' => $dataProvider,
            //'filter'=>$model,
            'columns' => array(
                'dealid',
                //'orderid',
                //'dealstatusid',
                'brandName',
                array(
                    'name' => 'AthleteName',
                    'type' => 'raw',
                //'value' => '$data->GetAthleteName()',
                ),
                array(
                    'name' => 'AgentName',
                    'type' => 'raw',
                //'value' => '$data->GetAgentName()',
                ),
                array(
                    'name' => 'dealType',
                //'type' => 'raw',
                //'value' => 'getdealtype($data->dealtype)',
                ),
                array(
                    'name' => 'cost',
                    'header' => 'Deal Cost (AUD)',
                    'htmlOptions' => array('class' => 'right'),
                ),
                array(
                    'name' => 'dealrequesteddate',
                    'htmlOptions' => array('class' => 'right'),
                ),
                array(
                    'name' => 'daysSinceOrdered',
                    'htmlOptions' => array('class' => 'right'),
                ),
                /* 'image',
                  'description',
                  'campaigndate',
                  'campaigntime',
                  'dealapproveddate',
                  'dealfullfilleddate',
                  'dateofpaymentbybrand',
                  'dateofpaymenttoagent',
                  'agentid',
                  'agentsharepercentage',
                  'agentshare',
                  'fulfill_engagement',
                  'fulfill_reach',
                  'fullfill_paidtoagent',
                 */
                array(
                    'class' => 'CButtonColumn',
                    'template' => '{view}',
                ),
            ),
        ));
        ?>

        <?php

        function getdealtype($dealtype) {

            if ($dealtype == 0) {
                echo 'Twitter';
            } else {
                echo 'Instagram';
            }
        }
        ?>
    </div>
</div>
<!-- /.row -->

gamechanger_admin/protected/views/deals/update.php
<?php
/* @var $this DealsController */
/* @var $model Deals */
//echo '<pre>'; var_dump($model->athlete); 
?>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header text-center text-uppercase">Deal #<?php echo $model->dealid; ?></h1>
    </div>
</div>
<!-- /.row -->

<?php $this->renderPartial('_update', array('model'=>$model)); ?>